name: RussianRoulette
version: 0.1
description: A Russian Roulette Plugin for fun
author: Kaede
 
main: moe.kaede.RR.RussianRoulette
 
commands:
  rr:
    description: Set yourself on fire.
    permission: roulette.rr
  sr:
    description: Set yourself on fire.
    permission: roulette.sr
  roulette:
    description: Set yourself on fire.
 
permissions:
  roulette.*:
    description: Gives access to all commands.
    children:
      roulette.rr: true
      roulette.sr: true
  roulette.rr:
    description: Allows you to start a roulette.
    default: op
  roulette.sr:
    description: Allows you to start a staff roulette.
    default: op
  roulette.srrank:
    description: Allows you to start a staff roulette.
    default: op
  roulette.admin:
    description: Allows you access to admin commands
    default: op